# Main navigation is defined in each page's front matter.
[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/gachuaa"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "rss"
    name       = "RSS feed"
    url        = "/index.xml"
    [social.params]
        icon = "rss"
