platforms:
  htb:
    label: Hack The Box
  thm:
    label: TryHackMe
  offsec:
    label: OffSec
  vuln-labs:
    label: Vuln Labs

topics:
  linux:
    label: Linux
  writeups:
    label: Write-ups
  offsec:
    label: OffSec
    parent: writeups
  htb:
    label: Hack The Box
    parent: writeups
  thm:
    label: TryHackMe
    parent: writeups
    